- name : Ensure packages.
  hosts: slave1
  tasks:
  - package: name=git state=latest
  
- name: "Example2: Add the line if it does not exist"
  hosts: localhost
  become: yes
  tasks:
  - lineinfile:
      path: /home/ubuntu/ansible/master.gitconfig
      line: "i'm awesome poip dddnonis "
      state: present
      backup: yes
  
- name: Ensure1 git file copied from master.
  hosts: slave1
  become: yes
  tasks:
  - copy: src=/home/ubuntu/ansible/master.gitconfig dest=/home/ubuntu/ansible/test.txt
  
- name: Return motd to registered var
  hosts: slave1
  become: yes
  tasks:
  - command: cat /home/ubuntu/ansible/test.txt
  
- name: Copy rpm file to server
  hosts: slave1
  become: yes
  copy:
    src: package.rpm
    dest: /tmp/package.rpm

- name: Install package.
  hosts: slave1
  become: yes
  yum:
     name: /tmp/package.rpm
     state: present
     
  
