- name : Ensure packages
  hosts: slave1
  tasks:
  - package: name=git state=latest
  
- name: Ensure1 git file copied from master
  hosts: slave1
  become: yes
  tasks:
  - copy: src=/home/ubuntu/ansible/master.gitconfig dest=~/.gitconfig
  
- name: Return motd to registered var
  hosts: slave1
  become: yes
  ansible.builtin.command: cat /home/ubuntu/ansible/test.txt
