- name : Ensure packages.
  hosts: slave1
  tasks:
  - package: name=git state=latest
  
- name: "Example2: Add the line if it does not exist"
  hosts: localhost
  connection: local
  become: yes
  sudo: yes
  tasks:
  - lineinfile:
      path: /home/ubuntu/ansible/master.gitconfig
      line: "LogLevel debug"
      state: present
      backup: yes
  
- name: Ensure1 git file copied from master.
  hosts: slave1
  become: yes
  tasks:
  - copy: src=/home/ubuntu/ansible/master.gitconfig dest=/home/ubuntu/ansible/test.txt
  
- name: Return motd to registered var
  hosts: slave1
  become: yes
  tasks:
  - command: cat /home/ubuntu/ansible/test.txt
     
  
